# <center>Linear Regression</center>

In [1]:
import pandas as pd

df = pd.read_csv("car_price.csv")
df.head(10)

,name,company,year,price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,"80,000","45,000 kms",Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,"4,25,000",40 kms,NaN
2,Maruti Suzuki Alto 800 Vxi,Maruti,2018,Ask For Price,"22,000 kms",Petrol
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,"3,25,000","28,000 kms",Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,"5,75,000","36,000 kms",Diesel
5,Ford EcoSport Titanium 1.5L TDCi,Ford,Temp Data,Ask For Price,"59,000 kms",Diesel
6,Ford Figo,Ford,2012,"1,75,000",Petrol,Diesel
7,Hyundai Eon,Hyundai,2013,"1,90,000","25,000 kms",Petrol
8,Ford EcoSport Ambiente 1.5L TDCi,Ford,2016,"8,30,000","24,530 kms",Diesel
9,Maruti Suzuki Alto K10 VXi AMT,Maruti,2015,"2,50,000","60,000 kms",Petrol

In [2]:
df['year'].unique()

array(['2007', '2006', '2018', '2014', 'Temp Data', '2012', '2013',
       '2016', '2015', '2010', '2017', '2008', '2011', '2019', '2009',
       '2005', '2000', '...', '150k', 'TOUR', '2003', 'r 15', '2004',
       'Zest', '/-Rs', 'sale', '1995', 'ara)', '2002', 'SELL', '2001',
       'tion', 'odel', '2 bs', 'arry', 'Eon', 'o...', 'ture', 'emi',
       'car', 'able', 'no.', 'd...', 'SALE', 'digo', 'sell', 'd Ex',
       'n...', 'e...', 'D...', ', Ac', 'go .', 'k...', 'o c4', 'zire',
       'cent', 'Sumo', 'cab', 't xe', 'EV2', 'r...', 'zest'], dtype=object)

## step-1

- check years values
- delete the inappropriate values
- change year data type

In [3]:
df = df[df['year'].str.isnumeric()] #taking only the numeric value rows
df['year'].unique()

array(['2007', '2006', '2018', '2014', '2012', '2013', '2016', '2015',
       '2010', '2017', '2008', '2011', '2019', '2009', '2005', '2000',
       '2003', '2004', '1995', '2002', '2001'], dtype=object)

In [4]:
df['year'] = df['year'].astype(int)
# df['year'].info()
df['year'].head(10)

0     2007
1     2006
2     2018
3     2014
4     2014
6     2012
7     2013
8     2016
9     2015
10    2010
Name: year, dtype: int32

## step-2

- check price values
- removing the comma
- change price data type

In [5]:
df['price'].unique()

array(['80,000', '4,25,000', 'Ask For Price', '3,25,000', '5,75,000',
       '1,75,000', '1,90,000', '8,30,000', '2,50,000', '1,82,000',
       '3,15,000', '4,15,000', '3,20,000', '10,00,000', '5,00,000',
       '3,50,000', '1,60,000', '3,10,000', '75,000', '1,00,000',
       '2,90,000', '95,000', '1,80,000', '3,85,000', '1,05,000',
       '6,50,000', '6,89,999', '4,48,000', '5,49,000', '5,01,000',
       '4,89,999', '2,80,000', '3,49,999', '2,84,999', '3,45,000',
       '4,99,999', '2,35,000', '2,49,999', '14,75,000', '3,95,000',
       '2,20,000', '1,70,000', '85,000', '2,00,000', '5,70,000',
       '1,10,000', '4,48,999', '18,91,111', '1,59,500', '3,44,999',
       '4,49,999', '8,65,000', '6,99,000', '3,75,000', '2,24,999',
       '12,00,000', '1,95,000', '3,51,000', '2,40,000', '90,000',
       '1,55,000', '6,00,000', '1,89,500', '2,10,000', '3,90,000',
       '1,35,000', '16,00,000', '7,01,000', '2,65,000', '5,25,000',
       '3,72,000', '6,35,000', '5,50,000', '4,85,000', '3,29,500',
       '2,51,111', '5,69,999', '69,999', '2,99,999', '3,99,999',
       '4,50,000', '2,70,000', '1,58,400', '1,79,000', '1,25,000',
       '2,99,000', '1,50,000', '2,75,000', '2,85,000', '3,40,000',
       '70,000', '2,89,999', '8,49,999', '7,49,999', '2,74,999',
       '9,84,999', '5,99,999', '2,44,999', '4,74,999', '2,45,000',
       '1,69,500', '3,70,000', '1,68,000', '1,45,000', '98,500',
       '2,09,000', '1,85,000', '9,00,000', '6,99,999', '1,99,999',
       '5,44,999', '1,99,000', '5,40,000', '49,000', '7,00,000', '55,000',
       '8,95,000', '3,55,000', '5,65,000', '3,65,000', '40,000',
       '4,00,000', '3,30,000', '5,80,000', '3,79,000', '2,19,000',
       '5,19,000', '7,30,000', '20,00,000', '21,00,000', '14,00,000',
       '3,11,000', '8,55,000', '5,35,000', '1,78,000', '3,00,000',
       '2,55,000', '5,49,999', '3,80,000', '57,000', '4,10,000',
       '2,25,000', '1,20,000', '59,000', '5,99,000', '6,75,000', '72,500',
       '6,10,000', '2,30,000', '5,20,000', '5,24,999', '4,24,999',
       '6,44,999', '5,84,999', '7,99,999', '4,44,999', '6,49,999',
       '9,44,999', '5,74,999', '3,74,999', '1,30,000', '4,01,000',
       '13,50,000', '1,74,999', '2,39,999', '99,999', '3,24,999',
       '10,74,999', '11,30,000', '1,49,000', '7,70,000', '30,000',
       '3,35,000', '3,99,000', '65,000', '1,69,999', '1,65,000',
       '5,60,000', '9,50,000', '7,15,000', '45,000', '9,40,000',
       '1,55,555', '15,00,000', '4,95,000', '8,00,000', '12,99,000',
       '5,30,000', '14,99,000', '32,000', '4,05,000', '7,60,000',
       '7,50,000', '4,19,000', '1,40,000', '15,40,000', '1,23,000',
       '4,98,000', '4,80,000', '4,88,000', '15,25,000', '5,48,900',
       '7,25,000', '99,000', '52,000', '28,00,000', '4,99,000',
       '3,81,000', '2,78,000', '6,90,000', '2,60,000', '90,001',
       '1,15,000', '15,99,000', '1,59,000', '51,999', '2,15,000',
       '35,000', '11,50,000', '2,69,000', '60,000', '4,30,000',
       '85,00,003', '4,01,919', '4,90,000', '4,24,000', '2,05,000',
       '5,49,900', '4,35,000', '1,89,700', '3,89,700', '3,60,000',
       '2,95,000', '1,14,990', '10,65,000', '4,70,000', '48,000',
       '1,88,000', '4,65,000', '1,79,999', '21,90,000', '23,90,000',
       '10,75,000', '4,75,000', '10,25,000', '6,15,000', '19,00,000',
       '14,90,000', '15,10,000', '18,50,000', '7,90,000', '17,25,000',
       '12,25,000', '68,000', '9,70,000', '31,00,000', '8,99,000',
       '88,000', '53,000', '5,68,500', '71,000', '5,90,000', '7,95,000',
       '42,000', '1,89,000', '1,62,000', '35,999', '29,00,000', '39,999',
       '50,500', '5,10,000', '8,60,000', '5,00,001'], dtype=object)

In [6]:
df = df[df['price'] != 'Ask For Price']
df['price'] = df['price'].str.replace(',', '')
# df['price'].info()
df['price'].head(10)

0      80000
1     425000
3     325000
4     575000
6     175000
7     190000
8     830000
9     250000
10    182000
11    315000
Name: price, dtype: object

## step-3

- check kms_driven values
- removing the comma 
- change kms_driven data type

In [7]:
df['kms_driven'].unique()

df['kms_driven'] = df['kms_driven'].str.split(' ').str.get(0).str.replace(',', '')
df['kms_driven'].head(10)

0      45000
1         40
3      28000
4      36000
6     Petrol
7      25000
8      24530
9      60000
10     60000
11     30000
Name: kms_driven, dtype: object

In [8]:
df = df[df['kms_driven'].str.isnumeric()]
df['kms_driven'] = df['kms_driven'].astype(int)
df.head(10)

,name,company,year,price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,80000,45000,Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,425000,40,NaN
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,325000,28000,Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,575000,36000,Diesel
7,Hyundai Eon,Hyundai,2013,190000,25000,Petrol
8,Ford EcoSport Ambiente 1.5L TDCi,Ford,2016,830000,24530,Diesel
9,Maruti Suzuki Alto K10 VXi AMT,Maruti,2015,250000,60000,Petrol
10,Skoda Fabia Classic 1.2 MPI,Skoda,2010,182000,60000,Petrol
11,Maruti Suzuki Stingray VXi,Maruti,2015,315000,30000,Petrol
12,Hyundai Elite i20 Magna 1.2,Hyundai,2014,415000,32000,Petrol

## step-4

- check fuel_type values

In [9]:
print(df['fuel_type'].unique())
df = df[~df['fuel_type'].isna()]
df

['Petrol' nan 'Diesel' 'LPG']

,name,company,year,price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,80000,45000,Petrol
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,325000,28000,Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,575000,36000,Diesel
7,Hyundai Eon,Hyundai,2013,190000,25000,Petrol
8,Ford EcoSport Ambiente 1.5L TDCi,Ford,2016,830000,24530,Diesel
...,...,...,...,...,...,...
883,Maruti Suzuki Ritz VXI ABS,Maruti,2011,270000,50000,Petrol
885,Tata Indica V2 DLE BS III,Tata,2009,110000,30000,Diesel
886,Toyota Corolla Altis,Toyota,2009,300000,132000,Petrol
888,Tata Zest XM Diesel,Tata,2018,260000,27000,Diesel
889,Mahindra Quanto C8,Mahindra,2013,390000,40000,Diesel

## step-5

- reset the indexes
- save the values in new csv file

In [10]:
df = df.reset_index(drop=True)
df.to_csv('cleaned_car_price.csv')

## Implement with the new cleaned file

In [11]:
ndf = pd.read_csv("cleaned_car_price.csv")
#ndf.iloc[row_start:row_end , col_start, col_end]
ndf = ndf.iloc[:, 1:]
ndf.head(10)

,name,company,year,price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,80000,45000,Petrol
1,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,325000,28000,Petrol
2,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,575000,36000,Diesel
3,Hyundai Eon,Hyundai,2013,190000,25000,Petrol
4,Ford EcoSport Ambiente 1.5L TDCi,Ford,2016,830000,24530,Diesel
5,Maruti Suzuki Alto K10 VXi AMT,Maruti,2015,250000,60000,Petrol
6,Skoda Fabia Classic 1.2 MPI,Skoda,2010,182000,60000,Petrol
7,Maruti Suzuki Stingray VXi,Maruti,2015,315000,30000,Petrol
8,Hyundai Elite i20 Magna 1.2,Hyundai,2014,415000,32000,Petrol
9,Mahindra Scorpio SLE BS IV,Mahindra,2015,320000,48660,Diesel

In [12]:
X = ndf[['name', 'company', 'year', 'kms_driven', 'fuel_type']]
X.head(10)

,name,company,year,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,45000,Petrol
1,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,28000,Petrol
2,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,36000,Diesel
3,Hyundai Eon,Hyundai,2013,25000,Petrol
4,Ford EcoSport Ambiente 1.5L TDCi,Ford,2016,24530,Diesel
5,Maruti Suzuki Alto K10 VXi AMT,Maruti,2015,60000,Petrol
6,Skoda Fabia Classic 1.2 MPI,Skoda,2010,60000,Petrol
7,Maruti Suzuki Stingray VXi,Maruti,2015,30000,Petrol
8,Hyundai Elite i20 Magna 1.2,Hyundai,2014,32000,Petrol
9,Mahindra Scorpio SLE BS IV,Mahindra,2015,48660,Diesel

In [13]:
Y = ndf['price']
Y.head(10)

0     80000
1    325000
2    575000
3    190000
4    830000
5    250000
6    182000
7    315000
8    415000
9    320000
Name: price, dtype: int64

In [14]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2)

In [15]:
from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder()

ohe.fit(X[['name','company','fuel_type']]) #changing categorical data to numerical

OneHotEncoder()

In [16]:
from sklearn.compose import make_column_transformer

column_trans = make_column_transformer(
    (
        OneHotEncoder(categories=ohe.categories_),
        ['name', 'company', 'fuel_type']),
    remainder = 'passthrough',
)

column_trans

ColumnTransformer(remainder='passthrough',
                  transformers=[('onehotencoder',
                                 OneHotEncoder(categories=[array(['Audi A3 Cabriolet 40 TFSI',
       'Audi A4 1.8 TFSI Multitronic Premium Plus',
       'Audi A4 2.0 TDI 177bhp Premium', 'Audi A6 2.0 TDI Premium',
       'Audi A8', 'Audi Q3 2.0 TDI quattro Premium',
       'Audi Q5 2.0 TDI quattro Premium Plus', 'Audi Q7',
       'BMW 3 Series 320d Sedan', 'BMW 3 Series 320i',
       'BMW 5 Series 52...
       'Volkswagen Vento Konekt Diesel Highline', 'Volvo S80 Summum D4'],
      dtype=object),
                                                           array(['Audi', 'BMW', 'Chevrolet', 'Datsun', 'Fiat', 'Force', 'Ford',
       'Hindustan', 'Honda', 'Hyundai', 'Jaguar', 'Jeep', 'Land',
       'Mahindra', 'Maruti', 'Mercedes', 'Mini', 'Mitsubishi', 'Nissan',
       'Renault', 'Skoda', 'Tata', 'Toyota', 'Volkswagen', 'Volvo'],
      dtype=object),
                                                           array(['Diesel', 'LPG', 'Petrol'], dtype=object)]),
                                 ['name', 'company', 'fuel_type'])])

In [17]:
from sklearn.linear_model import LinearRegression
from sklearn.pipeline import make_pipeline

lr = LinearRegression()
pipe = make_pipeline(column_trans, lr)
pipe

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(categories=[array(['Audi A3 Cabriolet 40 TFSI',
       'Audi A4 1.8 TFSI Multitronic Premium Plus',
       'Audi A4 2.0 TDI 177bhp Premium', 'Audi A6 2.0 TDI Premium',
       'Audi A8', 'Audi Q3 2.0 TDI quattro Premium',
       'Audi Q5 2.0 TDI quattro Premium Plus', 'Audi Q7',
       'BMW 3 Series 320d...
                                                                            array(['Audi', 'BMW', 'Chevrolet', 'Datsun', 'Fiat', 'Force', 'Ford',
       'Hindustan', 'Honda', 'Hyundai', 'Jaguar', 'Jeep', 'Land',
       'Mahindra', 'Maruti', 'Mercedes', 'Mini', 'Mitsubishi', 'Nissan',
       'Renault', 'Skoda', 'Tata', 'Toyota', 'Volkswagen', 'Volvo'],
      dtype=object),
                                                                            array(['Diesel', 'LPG', 'Petrol'], dtype=object)]),
                                                  ['name', 'company',
                                                   'fuel_type'])])),
                ('linearregression', LinearRegression())])

In [18]:
pipe.fit(X_train, Y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(categories=[array(['Audi A3 Cabriolet 40 TFSI',
       'Audi A4 1.8 TFSI Multitronic Premium Plus',
       'Audi A4 2.0 TDI 177bhp Premium', 'Audi A6 2.0 TDI Premium',
       'Audi A8', 'Audi Q3 2.0 TDI quattro Premium',
       'Audi Q5 2.0 TDI quattro Premium Plus', 'Audi Q7',
       'BMW 3 Series 320d...
                                                                            array(['Audi', 'BMW', 'Chevrolet', 'Datsun', 'Fiat', 'Force', 'Ford',
       'Hindustan', 'Honda', 'Hyundai', 'Jaguar', 'Jeep', 'Land',
       'Mahindra', 'Maruti', 'Mercedes', 'Mini', 'Mitsubishi', 'Nissan',
       'Renault', 'Skoda', 'Tata', 'Toyota', 'Volkswagen', 'Volvo'],
      dtype=object),
                                                                            array(['Diesel', 'LPG', 'Petrol'], dtype=object)]),
                                                  ['name', 'company',
                                                   'fuel_type'])])),
                ('linearregression', LinearRegression())])

In [19]:
X_test

,name,company,year,kms_driven,fuel_type
801,Hyundai Elite i20,Hyundai,2018,2100,Petrol
253,Maruti Suzuki Ritz VXI,Maruti,2014,19000,Petrol
470,Honda Amaze,Honda,2013,55700,Diesel
283,Mini Cooper S 1.6,Mini,2013,13000,Petrol
593,Hyundai Elite i20 Sportz 1.2,Hyundai,2017,15000,Petrol
...,...,...,...,...,...
266,Renault Kwid 1.0 RXT AMT,Renault,2018,10000,Petrol
281,Hyundai Accent GLX,Hyundai,2006,56000,Petrol
200,Mahindra Quanto C8,Mahindra,2013,20000,Diesel
488,Hyundai Grand i10 Magna AT 1.2 Kappa VTVT,Hyundai,2017,20000,Petrol
50,Maruti Suzuki Wagon R VXi BS III,Maruti,2013,39000,Petrol

In [20]:
Y_preds = pipe.predict(X_test)

Y_preds

array([ 549500.65264178,  330103.46031725,  314456.56736492,
       2255462.75882664,  471643.70287982,  278410.93167654,
        459808.12164058,  -15512.71463191,  396082.62233458,
        529873.18541458,  360326.35271522,  246094.89247105,
        433615.95721235,   98438.17637592,  292991.02751195,
        126241.82711955,  380562.71217102,  142643.00970821,
        234313.81580327,   50054.09305608,  438274.87661316,
        255857.30985292,  564669.09093225,  284228.81860733,
        408840.29479095,  744644.35143065,  744859.23950151,
        403017.77061321,  633661.8933496 ,  755719.6928854 ,
        533772.84157618,  322600.96570148,  125169.99550091,
        376623.35693514,  279128.10169829,  272093.99874204,
        666605.72447792,  189757.5388537 ,  623082.2362695 ,
        491179.3893953 ,  203240.55589931,  253483.79011992,
        520147.6539956 ,  387056.43529116,  334157.80538651,
       -148988.08330134,  226288.50952277,  412259.09380104,
        180694.88606368,   23698.05233999,  278537.31778358,
        770216.97434258, -128328.38536778,  486750.73022484,
        368571.43316053,  297359.06153833,  417680.62804517,
        480376.0126001 ,  214846.20499098,  297195.21853735,
       -134101.6722711 ,   19249.31313399,  394639.32159663,
        396374.52609823,  372935.95255227,  284119.21170951,
        443385.69647652,  339847.62011641,  327149.15589908,
        438274.87661316,  331706.16159581,  560630.09057866,
        477062.01741553,  426092.46071268,  382969.32716416,
       -305273.72628506,   66236.26706327,  542299.48533763,
        585131.6216036 ,  411557.50303382,  230869.25155463,
        870851.60784349,  316551.5982682 ,  248760.47532023,
        514493.1145119 ,  213729.65548587,  507073.55026225,
        827682.83461732,  467959.27664755,  113551.49287677,
        438906.87502107,  618094.67047445,  943469.17128304,
         21180.51918016,  585631.18276203,  425594.07984581,
        952390.1553745 ,  113254.97643551,  326315.60166597,
        219781.67520471,  613194.83620577,  145841.14534462,
        405409.98201812,  475617.85487848,  402651.33079427,
        129204.07815284,  -45605.06411782,  368227.06999022,
        142639.67387426,  579648.3302604 ,  630778.71876153,
        710330.31117921,  558252.69015183,  132569.01963457,
        465664.67251816,  635627.5256744 ,  440560.88626144,
         18053.72330945,  347695.51675853,  386355.81315878,
        300666.4545652 ,  390571.79455958,  292545.9083297 ,
        489558.0380411 ,  398642.978965  ,  474079.31734449,
        511772.14617506,  557473.19469216,  352282.28384992,
        195863.63462257,  198195.62101043,  452501.59697641,
        147546.6776785 ,  353087.52543434,  555229.28649658,
        333929.27052849,   21634.25816949,  598274.70224038,
        406196.60728686,  454763.19168947,  345826.27815983,
        195857.99202777, 1094204.98156946,  310053.37001811,
        199530.58319053,  596334.4687148 ,  280172.9568454 ,
        305828.44104254,  503715.03548428,  -44925.70293936,
        396515.65736636,  -25016.26936562,  464441.28174649,
        202501.61579434,  284205.17297572,  443761.53232101,
        245891.20248919, -124130.24189532,  504325.80865127,
         70205.18172387,  412971.24242666,  455617.99187196,
        257173.29898885])

In [ ]:
import numpy as np

res = pipe.predict(
    pd.DataFrame(
        columns = X_test.columns, 
        data=np.array(['Maruti Suzuki Swift', 'Maruti', 2019, 100, 'Petrol']).reshape(1,5)
    )
)

res

In [ ]:
print('>>>>>>>> Your predicted car price ' + str(res[0]) + ' <<<<<<<')